### ISSUE TITLE
Link text for Russian and Czech translations have ? in follow_full.php

### ISSUE THREAD

**Issue by fredricj** [petlof/liveresults#38]
In commit 5bc0543e2ddd779709b5c48ca41d4270d5493396 characters in the links for the Russian and Czech translations in follow_full.php was erroneously replaced with "?". The same happened in index.php but that was later fixed.

**Comment by xkenia** [comment]
Looks like fixed? Possible to close?

**Comment by fredricj** [comment]
yeah, fixed in ca26c96f17f8fdd17c1a638705eaa9123051e0cd
