### ISSUE TITLE
Error starting client with MySQL 8.0.29 and OLA 6.3.4 

### ISSUE THREAD

**Issue by arnesor** [petlof/liveresults#56]
I have a fresh install of MySQL 8.0.29 and OLA 6.3.4. OLA-Server is configured to use MySQL as a database and I have registered one simple competition. When I try to start Liveresults Client 2022-04-22, I get the following error when I click on the OLA SOFT button, select MySQL-Server, and enter the information for it (running on localhost): "Authentication method caching_sha2_password not supported by any of the available plugins".

I have tried to reconfigure MySQL (my.ini) by changing authentication policy to: `authentication_policy=mysql_native_password,,` and running the following command `
ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "password";
` as suggested by googling.

But then I get a lot of "Objektreferanse er ikke satt til en objektforekomst" errors instead. Bottom line: I'm unable to use LiveResult Client to report live results from the newest versions of OLA and MySQL.

**Comment by petlof** [comment]
Hi, this should be fixed with the latest version now
